server:
  port: 8889

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    password: 123456
    username: HUIREN
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver



  jpa:
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 2

mybatis:
  type-aliases-package: cn.gson.hui_ren_boot.model.pojos
  mapper-locations: classpath:mappers/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true

